Iter1
levshindenis/Loyalty-system-GO pull request #1
Opened 2024-02-19 14:32 UTC by levshindenis

2024-03-01 10:11 UTC, rktkov approved these changes

2024-03-06 22:09 UTC, rktkov requested changes

2024-03-06 22:09 UTC, rktkov commented on internal/app/models/worker.go
> +				panic(err)
Паники не стоит вызывать, лучше залоггировать ошибку и продолжить обработку. А то так получается, что она ошибка завершит выполнение всей программы.

2024-03-06 22:09 UTC, rktkov commented on internal/app/storages/server_storage.go
> +	go serv.FromDBToChannel(&serv.fromDB)
Надо бы передать контекст для валидного завершения горутины во время завершения программы. Тоже самое для  горутины ниже.

2024-03-06 22:09 UTC, rktkov commented on internal/app/storages/server_storage.go
> +				panic(err)
Тот же комментарий, что и выше по коду

2024-03-06 22:09 UTC, rktkov commented on internal/app/storages/server_storage.go
> +	ds     DBStorage
Тут лучше поле объявить через интерфейс, а не через структуру.

2024-03-06 22:09 UTC, rktkov commented on internal/app/models/worker.go
> +type CompareWorker struct {
Я бы вынес это в отдельный пакет и назвал бы его accural

2024-03-06 22:09 UTC, rktkov commented on internal/app/storages/server_storage.go
> +	"github.com/levshindenis/Loyalty-system-GO/internal/app/config"
Не забываем про группировку импортов.

2024-03-10 10:13 UTC, levshindenis commented on internal/app/storages/server_storage.go
> +	go serv.FromDBToChannel(&serv.fromDB)
В саму горутину контекст не передается, но у меня идет завершение горутины при закрытии канала в конце программы.

2024-03-10 10:13 UTC, levshindenis commented on internal/app/storages/server_storage.go
> +	go serv.FromDBToChannel(&serv.fromDB)
> Надо бы передать контекст для валидного завершения горутины во время завершения программы. Тоже самое для горутины ниже.

У меня в саму горутину контекст не передается, но горутина закрывается при закрытии канала в конце программы

2024-03-23 12:12 UTC, merged